name: Docker

on:
  push:
    branches:
      - master
      - test-*
      - 3.*
    tags:
      - 3.*

env:
  IMAGE_NAME: python

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: docker build . --file Dockerfile --tag $IMAGE_NAME

      - name: Log into registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push image
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository }}
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          [ "$VERSION" == "master" ] && VERSION=latest
          IMAGE_TAG=$IMAGE_ID:$VERSION

          echo IMAGE_TAG=$IMAGE_TAG

          docker tag $IMAGE_NAME $IMAGE_TAG
          docker push $IMAGE_TAG
